version: "3.8"

services: 
  nodejs:
    # Dockerfile build for Node.js
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_network
    restart: always
    ports: 
      - 300:300
    volumes: 
      - ./myapp:/app
      - /app/node_modules

    
