version: "3.8"

services: 
  nodejs:
    # Dockerfile build for Node.js
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    ports: 
      - 500:80
    volumes: 
      - ./myapp:/app
      - /app/node_modules
